In [1]:
import sys
sys.path.append("../")

In [2]:
# statement_name = "/Users/apenkin/workspace/personal/finman/data/Справка_о_движении_денежных_средств_241114.pdf"
# acc_name = "t-bank (main)"

statement_name = "../data/2025-01-19_Справка_о_движении_денежных_средств.pdf"
acc_name = "t-bank (main)"
# acc_name = "t-bank (proxy deposit)"

# statement_name = "../data/ozonbank_document_7093904.pdf"
# bank_name = "ozon"


# statement_name = "/Users/apenkin/workspace/personal/finman/data/Выписка_по_счёту_дебетовой_карты_241114.pdf"
# bank_name = "sber"

# statement_name = "../data/ya_241115.pdf"
# bank_name = "ya"

# 0. Настройка

In [3]:
from src.finman.utils.pdf import extract_text_from_pdf
from src.finman.expenses import tbank, ozon, sber, yapay
from src.finman.utils.gsheet import GSheetWorker

In [4]:
sheet_id = "1GqwNPuOtQUXfltK6F4oHpx-U1BqBgiDZfC5YfDcJyto"
gcreds_file = "../secrets/finman-433017-da308d823497.json"

gsw = GSheetWorker(gcreds_file)

In [5]:
spreadsheet_name = acc_name

if acc_name in ["t-bank (main)", "t-bank (deposit)", "t-bank (proxy deposit)"]:
    trans_col = "Сумма операции в валюте карты"
    date_col = "Дата операции"
    time_col = "Время операции"
    parse_operations = tbank.parse_operations
    extract_totals = tbank.extract_total_operations

elif bank_name == "ozon":
    trans_col = "Сумма операции"
    date_col = "Дата операции"
    time_col = "Время операции"
    spreadsheet_name = "ozon-bank (main)"
    parse_operations = ozon.parse_operations
    extract_totals = ozon.extract_total_operations

elif bank_name == "sber":
    trans_col = "Сумма в валюте счета"
    date_col = "Дата операции"
    time_col = "Время операции"
    spreadsheet_name = "сбер (main)"
    parse_operations = sber.parse_operations
    extract_totals = sber.extract_total_operations

elif bank_name == "ya":
    trans_col = "Сумма операции в валюте карты"
    date_col = "Дата операции"
    time_col = "Время операции"
    spreadsheet_name = "yapay (main)"
    parse_operations = yapay.parse_operations
    extract_totals = yapay.extract_total_operations

# 1. Прочитать выписку

In [6]:
text = extract_text_from_pdf(statement_name)

In [7]:
text

'Исх. № d54c3699\nАКЦИОНЕРНОЕ ОБЩЕСТВО «ТБАНК»\nРОССИЯ, 127287, МОСКВА, УЛ. 2-Я ХУТОРСКАЯ, Д. 38А, СТР. 26\nТЕЛ.: +7 495 648-10-00,  TBANK.RU\nСправка о движении средств\n19.01.2025\nПенкин Артем Александрович\nАдрес места жительства: 108809, Г Москва, Д Постниково, Ул Космическая, д. 11\nО продукте\nДата заключения договора:  31.08.2018\nНомер договора:  5086962189\nНомер лицевого счета:  40817810200006235175\nДвижение средств за период с 19.10.2024 по 19.01.2025\nДата и время\nоперации\nДата\nсписания\nСумма в валюте\nоперации\nСумма операции\nв валюте карты\nОписание\nоперации\nНомер\nкарты\n18.01.2025\n22:25\n19.01.2025\n04:00\n-3.00 ₽\n-3.00 ₽\nОплата в Vprok.ru\nPerekrestok MOSCOW RUS\n2475\n18.01.2025\n18:07\n18.01.2025\n18:13\n-1 665.00 ₽\n-1 665.00 ₽\nОплата в KANTATA\nMOSCOW RUS\n1665\n18.01.2025\n17:55\n18.01.2025\n17:56\n-1 700.00 ₽\n-1 700.00 ₽\nВнешний перевод по\nномеру телефона\n+79851334772\n5037\n18.01.2025\n16:27\n18.01.2025\n16:42\n-200.00 ₽\n-200.00 ₽\nОплата в PARKOVKA\nMOSKVA RUS\n1665\n18.01.2025\n14:29\n18.01.2025\n14:44\n-750.00 ₽\n-750.00 ₽\nОплата в CINEMA PARK 85\nMOSCOW RUS\n1665\n18.01.2025\n10:16\n18.01.2025\n10:31\n-506.00 ₽\n-506.00 ₽\nОплата в vkusvill\nCHERNOGOLOVKA RUS\n2475\n18.01.2025\n09:50\n18.01.2025\n10:05\n-3 545.00 ₽\n-3 545.00 ₽\nОплата в Vprok.ru\nPerekrestok MOSCOW RUS\n2475\n18.01.2025\n09:48\n18.01.2025\n10:31\n-2 104.00 ₽\n-2 104.00 ₽\nОплата в Yandex.Lavka\nMoskva RUS\n2475\n18.01.2025\n01:43\n18.01.2025\n01:43\n+716.00 ₽\n+716.00 ₽\nКэшбэк за обычные\nпокупки\n—\n17.01.2025\n22:02\n17.01.2025\n23:03\n-218.00 ₽\n-218.00 ₽\nОплата в Яндекс.Чаевые\n5037\n17.01.2025\n22:01\n17.01.2025\n23:03\n-2 395.00 ₽\n-2 395.00 ₽\nОплата в Яндекс Еда\n5037\n16.01.2025\n20:02\n16.01.2025\n20:17\n-3 820.00 ₽\n-3 820.00 ₽\nОплата в OOO LA FERTE\nMOSCOW RUS\n1665\n16.01.2025\n19:51\n17.01.2025\n03:30\n-1 209.00 ₽\n-1 209.00 ₽\nОплата в OZON Moskva RUS\n2475\n16.01.2025\n15:09\n16.01.2025\n15:24\n-430.00 ₽\n-430.00 ₽\nОплата в FRESH__ &__ GO.\nMOSCOW RUS\n1665\n16.01.2025\n11:23\n16.01.2025\n11:38\n-420.00 ₽\n-420.00 ₽\nОплата в KOFEJNYA\nMOSCOW RUS\n1665\n16.01.2025\n10:25\n18.01.2025\n13:58\n-7 430.00 ₽\n-7 430.00 ₽\nОплата в SOKOLNIKI 1 BKL\nMoskva RUS\n1665\nАО «ТБанк» универсальная лицензия Банка России № 2673, к/с 30101810145250000974 в ГУ Банка России по ЦФО\nБИК 044525974 ИНН 7710140679 КПП 771301001\n1\nДата и время\nоперации\nДата\nсписания\nСумма в валюте\nоперации\nСумма операции\nв валюте карты\nОписание\nоперации\nНомер\nкарты\n15.01.2025\n20:57\n15.01.2025\n21:49\n-1 739.00 ₽\n-1 739.00 ₽\nОплата в Yandex.Lavka\nMoskva RUS\n2475\n15.01.2025\n15:08\n15.01.2025\n19:11\n-1 724.00 ₽\n-1 724.00 ₽\nОплата в OZON Moskva RUS\n2475\n14.01.2025\n14:01\n14.01.2025\n14:16\n-380.00 ₽\n-380.00 ₽\nОплата в FRESH__ &__ GO.\nMOSCOW RUS\n1665\n14.01.2025\n11:15\n14.01.2025\n11:30\n-430.00 ₽\n-430.00 ₽\nОплата в KOFEJNYA\nMOSCOW RUS\n1665\n13.01.2025\n19:29\n13.01.2025\n19:44\n-1 236.00 ₽\n-1 236.00 ₽\nОплата в MSKAPT1741\nMOSCOW RUS\n1665\n13.01.2025\n19:26\n13.01.2025\n19:27\n-1 069.00 ₽\n-1 069.00 ₽\nОплата в\nVKUSVILL_8487_QR\n5037\n13.01.2025\n14:29\n13.01.2025\n14:44\n-6.00 ₽\n-6.00 ₽\nОплата в Vprok.ru\nPerekrestok MOSCOW RUS\n2475\n13.01.2025\n11:29\n13.01.2025\n11:44\n-199.00 ₽\n-199.00 ₽\nОплата в HH CAREER\nSERVICE MOSKVA RUS\n2475\n13.01.2025\n09:56\n13.01.2025\n10:11\n-8 020.00 ₽\n-8 020.00 ₽\nОплата в Vprok.ru\nPerekrestok MOSCOW RUS\n2475\n12.01.2025\n19:16\n12.01.2025\n19:31\n-2 869.00 ₽\n-2 869.00 ₽\nОплата в FORNERIIA\nMOSKVA RUS\n1665\n12.01.2025\n15:45\n12.01.2025\n16:00\n-2 200.00 ₽\n-2 200.00 ₽\nОплата в CHUK EVREJSKIJ\nMUZEJ MOSCOW RUS\n1665\n12.01.2025\n13:51\n13.01.2025\n13:37\n-4 190.00 ₽\n-4 190.00 ₽\nОплата в AZS 77735\nMOSCOW RUS\n1665\n12.01.2025\n09:07\n12.01.2025\n09:22\n-2 124.15 ₽\n-2 124.15 ₽\nОплата в vkusvill\nCHERNOGOLOVKA RUS\n2475\n11.01.2025\n17:09\n11.01.2025\n17:14\n-100.00 ₽\n-100.00 ₽\nОплата в IP RYABUSHKO\nYU.V. MOSCOW RUS\n1665\n11.01.2025\n15:51\n11.01.2025\n16:06\n-1 000.00 ₽\n-1 000.00 ₽\nОплата в GBUK GDM 3\nMOSCOW RUS\n1665\n10.01.2025\n21:38\n10.01.2025\n21:39\n-288.00 ₽\n-288.00 ₽\nОплата в\nVKUSVILL_8487_QR\n5037\n10.01.2025\n15:06\n10.01.2025\n15:14\n-5 000.00 ₽\n-5 000.00 ₽\nВнешний перевод по\nномеру телефона\n+79261659589\n5037\n09.01.2025\n20:53\n09.01.2025\n20:54\n-959.00 ₽\n-959.00 ₽\nОплата в\nVKUSVILL_8487_QR\n5037\n09.01.2025\n20:44\n09.01.2025\n20:59\n-2 608.00 ₽\n-2 608.00 ₽\nОплата в MSKAPT1741\nMOSCOW RUS\n1665\n09.01.2025\n17:25\n09.01.2025\n17:58\n-150.00 ₽\n-150.00 ₽\nОплата в PE KUZICHKINA\nELENA YU g Moskva RUS\n1665\n09.01.2025\n17:25\n09.01.2025\n17:40\n-3 510.00 ₽\n-3 510.00 ₽\nОплата в OOO Akusherstvo\nMOSKVA G RUS\n1665\n09.01.2025\n16:22\n09.01.2025\n16:37\n-699.00 ₽\n-699.00 ₽\nОплата в\nYANDEX*5815*PLUS\nMoscow RUS\n3685\n09.01.2025\n13:54\n09.01.2025\n14:09\n-612.00 ₽\n-612.00 ₽\nОплата в VV_8487_KCO_4\nMOSCOW RUS\n1665\n08.01.2025\n11:43\n08.01.2025\n17:22\n-1 241.00 ₽\n-1 241.00 ₽\nОплата в OZON Moskva RUS\n2475\n08.01.2025\n10:30\n08.01.2025\n10:45\n-348.00 ₽\n-348.00 ₽\nОплата в VV_8487_CAFE_6\nMOSCOW RUS\n1665\n08.01.2025\n10:14\n08.01.2025\n10:29\n-2 907.00 ₽\n-2 907.00 ₽\nОплата в GEKOLAB\nMOSCOW RUS\n1665\n07.01.2025\n15:15\n07.01.2025\n19:20\n-1 846.00 ₽\n-1 846.00 ₽\nОплата в OZON Moskva RUS\n2475\nАО «ТБанк» универсальная лицензия Банка России № 2673, к/с 30101810145250000974 в ГУ Банка России по ЦФО\nБИК 044525974 ИНН 7710140679 КПП 771301001\n2\nДата и время\nоперации\nДата\nсписания\nСумма в валюте\nоперации\nСумма операции\nв валюте карты\nОписание\nоперации\nНомер\nкарты\n06.01.2025\n19:22\n06.01.2025\n19:59\n-1 752.00 ₽\n-1 752.00 ₽\nОплата в Yandex.Lavka\nMoskva RUS\n2475\n06.01.2025\n16:42\n06.01.2025\n17:01\n-336.00 ₽\n-336.00 ₽\nОплата в YM*weasel g\nSankt-Peter RUS\n5037\n06.01.2025\n15:32\n08.01.2025\n15:30\n-16 022.00 ₽\n-16 022.00 ₽\nОплата в GLEMPING\nZELENAYA TROP Volkovichi\nRUS\n1665\n06.01.2025\n15:21\n06.01.2025\n15:37\n-2 300.00 ₽\n-2 300.00 ₽\nОплата в CP* DDX\nFITNESS22 MOSKVA RUS\n2475\n06.01.2025\n10:35\n06.01.2025\n10:36\n-245.00 ₽\n-245.00 ₽\nОплата в Ресторан Зеленая\nТ_P_QR\n5037\n05.01.2025\n20:53\n05.01.2025\n21:08\n-2 990.00 ₽\n-2 990.00 ₽\nОплата в RESTORAN\nZELENAYA TROP Volkovichi\nRUS\n1665\n05.01.2025\n12:56\n05.01.2025\n13:11\n-2 890.00 ₽\n-2 890.00 ₽\nОплата в Apteka Gorzdrav\nMOSKVA G RUS\n1665\n05.01.2025\n12:27\n05.01.2025\n12:42\n-2 472.15 ₽\n-2 472.15 ₽\nОплата в BRATYA\nKARAVAEVY MOSCOW RUS\n1665\n05.01.2025\n12:07\n05.01.2025\n12:07\n+87.00 ₽\n+87.00 ₽\nВозврат средств по\nоперации оплаты Vprok.ru\nPerekrestok MOSCOW RUS\n2475\n05.01.2025\n12:06\n05.01.2025\n12:06\n+643.81 ₽\n+643.81 ₽\nВозврат средств по\nоперации оплаты Vprok.ru\nPerekrestok MOSCOW RUS\n2475\n04.01.2025\n16:57\n04.01.2025\n17:12\n-880.00 ₽\n-880.00 ₽\nОплата в SP_MUZEJ\nKolomna RUS\n1665\n04.01.2025\n16:45\n04.01.2025\n16:45\n-650.00 ₽\n-650.00 ₽\nВнутренний перевод на\nдоговор 5339651035\n5037\n04.01.2025\n16:39\n04.01.2025\n16:54\n-2 100.00 ₽\n-2 100.00 ₽\nОплата в KONDITERSKAYA\nV SADU Kolomna RUS\n1665\n04.01.2025\n15:30\n04.01.2025\n15:50\n-13 250.00 ₽\n-13 250.00 ₽\nОплата в\nPAW*comfortbooking Sankt-\nPeterbu RUS\n2475\n04.01.2025\n13:17\n04.01.2025\n13:17\n-674.00 ₽\n-674.00 ₽\nОплата в АЗС №84\n5037\n04.01.2025\n13:15\n04.01.2025\n13:16\n-2 599.70 ₽\n-2 599.70 ₽\nОплата в АЗС №84\n5037\n04.01.2025\n09:22\n04.01.2025\n09:59\n-1 471.00 ₽\n-1 471.00 ₽\nОплата в Yandex.Lavka\nMoskva RUS\n2475\n04.01.2025\n08:55\n04.01.2025\n09:10\n-1 500.00 ₽\n-1 500.00 ₽\nОплата в YM *firstbyte rus\nMoscow RUS\n2475\n03.01.2025\n22:14\n04.01.2025\n02:46\n-5 988.00 ₽\n-5 988.00 ₽\nОплата в\nPAW*comfortbooking Sankt-\nPeterbu RUS\n2475\n03.01.2025\n21:18\n03.01.2025\n21:33\n-1 140.00 ₽\n-1 140.00 ₽\nОплата в MSKAPT1741\nMOSCOW RUS\n1665\n03.01.2025\n19:21\n03.01.2025\n19:36\n-2 351.00 ₽\n-2 351.00 ₽\nОплата в\nYANDEX*5814*YANDEX\nEDA MOSCOW RUS\n3685\n03.01.2025\n18:22\n03.01.2025\n20:22\n-505.70 ₽\n-505.70 ₽\nОплата в CITYDRIVE\nMOSCOW RUS\n2475\n03.01.2025\n18:02\n03.01.2025\n20:02\n-500.00 ₽\n-500.00 ₽\nОплата в CITYDRIVE\nMOSCOW RUS\n2475\n03.01.2025\n14:46\n03.01.2025\n14:46\n-5 000.00 ₽\n-5 000.00 ₽\nВнешний перевод по\nномеру телефона\n+79261659589\n5037\nАО «ТБанк» универсальная лицензия Банка России № 2673, к/с 30101810145250000974 в ГУ Банка России по ЦФО\nБИК 044525974 ИНН 7710140679 КПП 771301001\n3\nДата и время\nоперации\nДата\nсписания\nСумма в валюте\nоперации\nСумма операции\nв валюте карты\nОписание\nоперации\nНомер\nкарты\n03.01.2025\n09:49\n03.01.2025\n09:49\n-120 000.00 ₽\n-120 000.00 ₽\nВнешний перевод по\nномеру телефона\n+79104528167\n5037\n02.01.2025\n19:05\n02.01.2025\n19:20\n-597.00 ₽\n-597.00 ₽\nОплата в MSKAPT1741\nMOSCOW RUS\n1665\n31.12.2024\n22:09\n01.01.2025\n03:22\n-923.00 ₽\n-923.00 ₽\nОплата в YandexGo Moskva\nRUS\n2475\n31.12.2024\n21:35\n01.01.2025\n03:05\n-1 235.00 ₽\n-1 235.00 ₽\nОплата в YandexGo Moskva\nRUS\n2475\n31.12.2024\n20:06\n31.12.2024\n20:11\n-1 000.00 ₽\n-1 000.00 ₽\nОплата в PAY.MTS.RU\nTOPUP 8297 MOSCOW RUS\n3685\n31.12.2024\n19:04\n31.12.2024\n19:09\n-730.00 ₽\n-730.00 ₽\nОплата в BEELINE SVYAZ\nMOSKVA RUS\n2475\n31.12.2024\n19:02\n31.12.2024\n19:02\n+370 000.00 ₽\n+370 000.00 ₽\nВнутрибанковский перевод\nс договора 8187622573\n5037\n31.12.2024\n12:05\n31.12.2024\n12:06\n-99.00 ₽\n-99.00 ₽\nОплата в Продукты_P_QR\n5037\n31.12.2024\n12:04\n31.12.2024\n12:04\n-200.00 ₽\n-200.00 ₽\nОплата в\nVKUSVILL_8487_QR\n5037\n31.12.2024\n12:03\n31.12.2024\n12:04\n-613.00 ₽\n-613.00 ₽\nОплата в\nVKUSVILL_8487_QR\n5037\n31.12.2024\n03:02\n31.12.2024\n03:17\n-87.00 ₽\n-87.00 ₽\nОплата в Vprok.ru\nPerekrestok MOSCOW RUS\n2475\n30.12.2024\n19:03\n30.12.2024\n19:04\n-2 882.00 ₽\n-2 882.00 ₽\nОплата в KHLH Мск ТЦ\nСокольники\n5037\n30.12.2024\n18:17\n30.12.2024\n18:32\n-200.00 ₽\n-200.00 ₽\nОплата в FOTOMASTER\nMOSCOW RUS\n1665\n30.12.2024\n17:34\n30.12.2024\n17:36\n-2 174.96 ₽\n-2 174.96 ₽\nОплата в Winelab\n5037\n30.12.2024\n14:28\n30.12.2024\n14:44\n-200.00 ₽\n-200.00 ₽\nОплата в CVETNOJ\nCENTRAL MARKET MOSKVA\nRUS\n1665\n30.12.2024\n14:16\n30.12.2024\n14:31\n-10 994.00 ₽\n-10 994.00 ₽\nОплата в Vprok.ru\nPerekrestok MOSCOW RUS\n2475\n30.12.2024\n14:15\n30.12.2024\n14:16\n+8 000.00 ₽\n+8 000.00 ₽\nВнутрибанковский перевод\nс договора 8187622573\n5037\n30.12.2024\n14:14\n30.12.2024\n14:16\n+6 000.00 ₽\n+6 000.00 ₽\nВнутрибанковский перевод\nс договора 8187622573\n5037\n30.12.2024\n11:24\n30.12.2024\n11:39\n-3 180.00 ₽\n-3 180.00 ₽\nОплата в MASA MADRE\nMOSCOW RUS\n1665\n29.12.2024\n21:53\n29.12.2024\n21:54\n-3 124.00 ₽\n-3 124.00 ₽\nОплата в ООО "Аптечная\nсеть Оз"\n5037\n29.12.2024\n20:47\n29.12.2024\n21:02\n-2 930.00 ₽\n-2 930.00 ₽\nОплата в OOO LA FERTE\nMOSCOW RUS\n1665\n29.12.2024\n19:43\n29.12.2024\n19:44\n+10 000.00 ₽\n+10 000.00 ₽\nВнутрибанковский перевод\nс договора 8187622573\n5037\n29.12.2024\n15:46\n29.12.2024\n16:01\n-500.00 ₽\n-500.00 ₽\nОплата в PAVELECKAYA\nPLAZA MOSCOW RUS\n1665\n29.12.2024\n14:49\n29.12.2024\n15:04\n-360.00 ₽\n-360.00 ₽\nОплата в ONE SPECIAL\nMOSCOW RUS\n1665\n29.12.2024\n14:47\n29.12.2024\n15:02\n-670.00 ₽\n-670.00 ₽\nОплата в CINNABON\nMOSKVA RUS\n1665\n29.12.2024\n14:21\n29.12.2024\n14:36\n-1 000.00 ₽\n-1 000.00 ₽\nОплата в YM*AMPP\nMOSCOW RUS\n2475\n29.12.2024\n13:35\n29.12.2024\n13:51\n-390.00 ₽\n-390.00 ₽\nОплата в FARSH F-15\nMOSCOW RUS\n1665\nАО «ТБанк» универсальная лицензия Банка России № 2673, к/с 30101810145250000974 в ГУ Банка России по ЦФО\nБИК 044525974 ИНН 7710140679 КПП 771301001\n4\nДата и время\nоперации\nДата\nсписания\nСумма в валюте\nоперации\nСумма операции\nв валюте карты\nОписание\nоперации\nНомер\nкарты\n29.12.2024\n13:12\n29.12.2024\n13:27\n-1 455.00 ₽\n-1 455.00 ₽\nОплата в FARSH F-15\nMOSCOW RUS\n1665\n28.12.2024\n21:25\n28.12.2024\n21:40\n-140.00 ₽\n-140.00 ₽\nОплата в MSKAPT1741\nMOSCOW RUS\n1665\n28.12.2024\n15:51\n29.12.2024\n18:49\n-1 000.00 ₽\n-1 000.00 ₽\nОперация в других\nкредитных организациях\nYandexBank_C2A g. Moskva\nRUS\n3685\n27.12.2024\n12:16\n28.12.2024\n16:47\n-1 000.00 ₽\n-1 000.00 ₽\nОперация в других\nкредитных организациях\nYandexBank_C2A g. Moskva\nRUS\n3685\n27.12.2024\n12:11\n28.12.2024\n19:04\n-2 472.00 ₽\n-2 472.00 ₽\nОперация в других\nкредитных организациях\nYandexBank_C2A g. Moskva\nRUS\n3685\n26.12.2024\n21:50\n27.12.2024\n04:17\n-985.55 ₽\n-985.55 ₽\nОплата в VV_8487_KCO_4\nMOSCOW RUS\n1665\n26.12.2024\n15:09\n26.12.2024\n15:24\n-350.00 ₽\n-350.00 ₽\nОплата в FRESH__ &__ GO.\nMOSCOW RUS\n1665\n26.12.2024\n11:21\n26.12.2024\n11:36\n-420.00 ₽\n-420.00 ₽\nОплата в KOFEJNYA\nMOSCOW RUS\n1665\n25.12.2024\n23:31\n26.12.2024\n03:51\n+4 200.00 ₽\n+4 200.00 ₽\nВнутрибанковский перевод\nс договора 5263020603\n5037\n25.12.2024\n23:28\n26.12.2024\n03:34\n-18 490.00 ₽\n-18 490.00 ₽\nОплата в LIONS HEAD\nMOSCOW RUS\n1665\n25.12.2024\n23:27\n26.12.2024\n03:51\n+20 000.00 ₽\n+20 000.00 ₽\nВнутрибанковский перевод\nс договора 8187622573\n5037\n25.12.2024\n13:04\n25.12.2024\n13:04\n-1 662.50 ₽\n-1 662.50 ₽\nОплата в Сервисы Яндекса\n5037\n24.12.2024\n21:28\n24.12.2024\n21:29\n+2 000.00 ₽\n+2 000.00 ₽\nВнутрибанковский перевод\nс договора 5044083052\n5037\n24.12.2024\n20:36\n24.12.2024\n20:36\n+4 000.00 ₽\n+4 000.00 ₽\nВнутрибанковский перевод\nс договора 5158775592\n5037\n24.12.2024\n17:53\n24.12.2024\n18:29\n-297.00 ₽\n-297.00 ₽\nОплата в IP Shporunenko Y\nA g Moskva RUS\n1665\n24.12.2024\n09:28\n24.12.2024\n09:44\n-1 095.00 ₽\n-1 095.00 ₽\nОплата в BRATYA\nKARAVAEVY MOSCOW RUS\n1665\n23.12.2024\n20:27\n23.12.2024\n20:27\n+3 500.00 ₽\n+3 500.00 ₽\nВнутрибанковский перевод\nс договора 8187622573\n5037\n23.12.2024\n20:26\n23.12.2024\n20:27\n-3 500.00 ₽\n-3 500.00 ₽\nПеревод на карту другого\nбанка\n5037\n23.12.2024\n13:14\n23.12.2024\n13:15\n-8 300.00 ₽\n-8 300.00 ₽\nПеревод на карту другого\nбанка\n5037\n23.12.2024\n13:13\n23.12.2024\n13:13\n+8 300.00 ₽\n+8 300.00 ₽\nВнутрибанковский перевод\nс договора 8187622573\n5037\n23.12.2024\n10:57\n23.12.2024\n11:12\n-570.00 ₽\n-570.00 ₽\nОплата в KOFEJNYA\nMOSCOW RUS\n1665\n23.12.2024\n09:52\n23.12.2024\n10:07\n-6 931.00 ₽\n-6 931.00 ₽\nОплата в Vprok.ru\nPerekrestok MOSCOW RUS\n2475\n22.12.2024\n19:44\n22.12.2024\n19:59\n-410.00 ₽\n-410.00 ₽\nОплата в VASHA 1 MOSCOW\nRUS\n1665\n22.12.2024\n19:40\n22.12.2024\n19:42\n-3 700.00 ₽\n-3 700.00 ₽\nОплата в OSOBENNYI\nBARBER\n5037\nАО «ТБанк» универсальная лицензия Банка России № 2673, к/с 30101810145250000974 в ГУ Банка России по ЦФО\nБИК 044525974 ИНН 7710140679 КПП 771301001\n5\nДата и время\nоперации\nДата\nсписания\nСумма в валюте\nоперации\nСумма операции\nв валюте карты\nОписание\nоперации\nНомер\nкарты\n22.12.2024\n14:11\n23.12.2024\n17:15\n-1 377.00 ₽\n-1 377.00 ₽\nОперация в других\nкредитных организациях\nYandexBank_C2A g. Moskva\nRUS\n3685\n22.12.2024\n10:05\n22.12.2024\n10:05\n-386.00 ₽\n-386.00 ₽\nОплата в\nVKUSVILL_8487_QR\n5037\n21.12.2024\n20:13\n21.12.2024\n20:28\n-495.00 ₽\n-495.00 ₽\nОплата в MSKAPT1741\nMOSCOW RUS\n1665\n21.12.2024\n08:58\n22.12.2024\n13:24\n-1 628.00 ₽\n-1 628.00 ₽\nОперация в других\nкредитных организациях\nYandexBank_C2A g. Moskva\nRUS\n3685\n21.12.2024\n08:51\n21.12.2024\n09:06\n-690.87 ₽\n-690.87 ₽\nОплата в vkusvill\nCHERNOGOLOVKA RUS\n2475\n21.12.2024\n08:41\n21.12.2024\n08:56\n-1 014.00 ₽\n-1 014.00 ₽\nОплата в\nYANDEX*5411*YANDEX\nEDA MOSCOW RUS\n3685\n20.12.2024\n17:12\n20.12.2024\n17:13\n-5 000.00 ₽\n-5 000.00 ₽\nВнешний перевод по\nномеру телефона\n+79261659589\n5037\n20.12.2024\n11:35\n20.12.2024\n15:39\n-1 879.00 ₽\n-1 879.00 ₽\nОплата в OZON Moskva RUS\n2475\n20.12.2024\n09:57\n20.12.2024\n10:13\n-990.00 ₽\n-990.00 ₽\nОплата в vkusvill\nCHERNOGOLOVKA RUS\n2475\n19.12.2024\n22:05\n20.12.2024\n03:08\n-1 791.00 ₽\n-1 791.00 ₽\nОплата в YandexGo Moskva\nRUS\n2475\n19.12.2024\n21:25\n19.12.2024\n21:25\n-1 235.00 ₽\n-1 235.00 ₽\nОплата в НЕТМОНЕТ\n5037\n19.12.2024\n21:23\n19.12.2024\n21:38\n-10 281.00 ₽\n-10 281.00 ₽\nОплата в IFLES MOSKVA\nRUS\n1665\n19.12.2024\n18:21\n19.12.2024\n18:36\n-2 620.00 ₽\n-2 620.00 ₽\nОплата в LIROUAGE\nMOSKVA RUS\n1665\n19.12.2024\n15:50\n19.12.2024\n16:05\n-190.00 ₽\n-190.00 ₽\nОплата в FRESH__ &__ GO.\nMOSCOW RUS\n1665\n19.12.2024\n15:50\n19.12.2024\n16:06\n-470.00 ₽\n-470.00 ₽\nОплата в FRESH__ &__ GO.\nMOSCOW RUS\n1665\n19.12.2024\n15:39\n19.12.2024\n15:55\n-1 845.00 ₽\n-1 845.00 ₽\nОплата в NEO-FARM\nMOSCOW RUS\n1665\n19.12.2024\n13:41\n19.12.2024\n13:42\n-13 000.00 ₽\n-13 000.00 ₽\nПеревод на карту другого\nбанка\n5037\n19.12.2024\n10:58\n19.12.2024\n11:13\n-420.00 ₽\n-420.00 ₽\nОплата в KOFEJNYA\nMOSCOW RUS\n1665\n19.12.2024\n09:25\n19.12.2024\n09:30\n-1 100.00 ₽\n-1 100.00 ₽\nОплата в PAY.MTS.RU\nTOPUP 8297 MOSCOW RUS\n3685\n19.12.2024\n08:28\n20.12.2024\n14:34\n-1 000.00 ₽\n-1 000.00 ₽\nОперация в других\nкредитных организациях\nYandexBank_C2A g. Moskva\nRUS\n3685\n18.12.2024\n15:40\n18.12.2024\n15:55\n-29 799.60 ₽\n-29 799.60 ₽\nОплата в ROLF4 MOSCOW\nRUS\n1665\n18.12.2024\n13:24\n18.12.2024\n13:24\n+1 680.00 ₽\n+1 680.00 ₽\nОтмена операции оплаты\nSTOLOVAYA MOSCOW RUS\n1665\n18.12.2024\n13:20\n18.12.2024\n13:35\n-1 290.00 ₽\n-1 290.00 ₽\nОплата в STOLOVAYA\nMOSCOW RUS\n1665\n18.12.2024\n12:55\n18.12.2024\n13:10\n-1 680.00 ₽\n-1 680.00 ₽\nОплата в STOLOVAYA\nMOSCOW RUS\n1665\nАО «ТБанк» универсальная лицензия Банка России № 2673, к/с 30101810145250000974 в ГУ Банка России по ЦФО\nБИК 044525974 ИНН 7710140679 КПП 771301001\n6\nДата и время\nоперации\nДата\nсписания\nСумма в валюте\nоперации\nСумма операции\nв валюте карты\nОписание\nоперации\nНомер\nкарты\n17.12.2024\n22:54\n17.12.2024\n22:54\n+1 445.00 ₽\n+1 445.00 ₽\nКэшбэк за обычные\nпокупки\n—\n17.12.2024\n14:58\n17.12.2024\n15:13\n-630.00 ₽\n-630.00 ₽\nОплата в FRESH__ &__ GO.\nMOSCOW RUS\n1665\n17.12.2024\n11:45\n17.12.2024\n12:00\n-500.00 ₽\n-500.00 ₽\nОплата в YM*AMPP\nMOSCOW RUS\n2475\n17.12.2024\n11:37\n17.12.2024\n11:38\n-1 407.00 ₽\n-1 407.00 ₽\nОплата в НЕТМОНЕТ\n5037\n16.12.2024\n20:43\n16.12.2024\n20:58\n-982.60 ₽\n-982.60 ₽\nОплата в vkusvill\nCHERNOGOLOVKA RUS\n2475\n16.12.2024\n11:48\n16.12.2024\n12:04\n-420.00 ₽\n-420.00 ₽\nОплата в KOFEJNYA\nMOSCOW RUS\n1665\n16.12.2024\n11:41\n16.12.2024\n11:41\n+79 000.00 ₽\n+79 000.00 ₽\nВнутрибанковский перевод\nс договора 8187622573\n5037\n16.12.2024\n11:40\n16.12.2024\n11:41\n-79 000.00 ₽\n-79 000.00 ₽\nСнятие наличных. Т-Банк,\n2418 Москва Россия\n1665\n16.12.2024\n08:10\n16.12.2024\n08:25\n-2 202.00 ₽\n-2 202.00 ₽\nОплата в MSKAPT1741\nMOSCOW RUS\n1665\n15.12.2024\n12:39\n16.12.2024\n16:32\n-1 000.00 ₽\n-1 000.00 ₽\nОперация в других\nкредитных организациях\nYandexBank_C2A g. Moskva\nRUS\n3685\n14.12.2024\n20:11\n15.12.2024\n03:28\n-896.00 ₽\n-896.00 ₽\nОплата в OZON Moskva RUS\n2475\n14.12.2024\n20:02\n15.12.2024\n14:00\n-1 058.00 ₽\n-1 058.00 ₽\nОперация в других\nкредитных организациях\nYandexBank_C2A g. Moskva\nRUS\n3685\n14.12.2024\n17:14\n14.12.2024\n17:29\n-2 820.75 ₽\n-2 820.75 ₽\nОплата в YM*ornament-mag\ng. Moskva RUS\n5037\n14.12.2024\n16:52\n14.12.2024\n17:07\n-1 850.00 ₽\n-1 850.00 ₽\nОплата в SASHA BRED.\nBorki RUS\n1665\n14.12.2024\n11:50\n14.12.2024\n12:05\n-700.00 ₽\n-700.00 ₽\nОплата в GRIL BAR\nMOSCOW RUS\n1665\n14.12.2024\n11:03\n14.12.2024\n11:18\n-2 550.00 ₽\n-2 550.00 ₽\nОплата в OCHAKOVO\nMOSCOW RUS\n1665\n14.12.2024\n08:07\n15.12.2024\n16:52\n-400.00 ₽\n-400.00 ₽\nОперация в других\nкредитных организациях\nYandexBank_C2A g. Moskva\nRUS\n3685\n13.12.2024\n20:57\n13.12.2024\n21:12\n-1 049.96 ₽\n-1 049.96 ₽\nОплата в PYATEROCHKA\n23568 MOSCOW RUS\n1665\n13.12.2024\n20:49\n13.12.2024\n20:50\n-1 532.33 ₽\n-1 532.33 ₽\nОплата в\nVKUSVILL_8487_QR\n5037\n13.12.2024\n16:53\n13.12.2024\n17:01\n-5 000.00 ₽\n-5 000.00 ₽\nПеревод на карту другого\nбанка\n5037\n13.12.2024\n13:50\n14.12.2024\n13:17\n-2 000.00 ₽\n-2 000.00 ₽\nОперация в других\nкредитных организациях\nYandexBank_C2A g. Moskva\nRUS\n3685\n12.12.2024\n20:56\n13.12.2024\n03:17\n-160.00 ₽\n-160.00 ₽\nОплата в KAFE LABIRINT g\nMoskva RUS\n1665\n12.12.2024\n20:55\n13.12.2024\n03:16\n-100.00 ₽\n-100.00 ₽\nОплата в KAFE LABIRINT 

In [8]:
transactions_df = parse_operations(text)

In [9]:
# import re
# import pandas as pd
# from datetime import datetime

In [10]:
transactions_df

,id,Дата операции,Время операции,Сумма операции в валюте карты,Валюта карты,Сумма в валюте операции,Валюта операции,Описание операции,Номер карты
0,75c693f91e,2025-01-18,2025-01-18 22:25:00,-3.00,₽,-3.00,₽,Оплата в Vprok.ru Perekrestok MOSCOW RUS,2475
1,bf35820f73,2025-01-18,2025-01-18 18:07:00,-1665.00,₽,-1665.00,₽,Оплата в KANTATA MOSCOW RUS,1665
2,6fd3005c5a,2025-01-18,2025-01-18 17:55:00,-1700.00,₽,-1700.00,₽,Внешний перевод по номеру телефона +79851334772,5037
3,e5aee65b11,2025-01-18,2025-01-18 16:27:00,-200.00,₽,-200.00,₽,Оплата в PARKOVKA MOSKVA RUS,1665
4,a8bfb6a013,2025-01-18,2025-01-18 14:29:00,-750.00,₽,-750.00,₽,Оплата в CINEMA PARK 85 MOSCOW RUS,1665
...,...,...,...,...,...,...,...,...,...
492,ff9e6022ac,2024-10-19,2024-10-19 14:35:00,-279.61,₽,-279.61,₽,Оплата в BELKACAR MOSKVA RUS,5223
493,80adc25fc7,2024-10-19,2024-10-19 13:54:00,-2554.00,₽,-2554.00,₽,Оплата в QSR,2911
494,5a21d06697,2024-10-19,2024-10-19 12:36:00,108.00,₽,108.00,₽,Отмена операции оплаты YANDEX*5411*LAVKA Mosco...,3685
495,0d00a3d382,2024-10-19,2024-10-19 10:04:00,-2590.00,₽,-2590.00,₽,Оплата в BELKACAR MOSKVA RUS,5223
496,02992efcd2,2024-10-19,2024-10-19 08:40:00,-704.00,₽,-704.00,₽,Оплата в YANDEX*5411*LAVKA Moscow RUS,3685

In [11]:
incomes, expences = extract_totals(text)
incomes, expences

(13174252.36, 13165371.74)

In [12]:
transactions_df.head()

,id,Дата операции,Время операции,Сумма операции в валюте карты,Валюта карты,Сумма в валюте операции,Валюта операции,Описание операции,Номер карты
0,75c693f91e,2025-01-18,2025-01-18 22:25:00,-3.0,₽,-3.0,₽,Оплата в Vprok.ru Perekrestok MOSCOW RUS,2475
1,bf35820f73,2025-01-18,2025-01-18 18:07:00,-1665.0,₽,-1665.0,₽,Оплата в KANTATA MOSCOW RUS,1665
2,6fd3005c5a,2025-01-18,2025-01-18 17:55:00,-1700.0,₽,-1700.0,₽,Внешний перевод по номеру телефона +79851334772,5037
3,e5aee65b11,2025-01-18,2025-01-18 16:27:00,-200.0,₽,-200.0,₽,Оплата в PARKOVKA MOSKVA RUS,1665
4,a8bfb6a013,2025-01-18,2025-01-18 14:29:00,-750.0,₽,-750.0,₽,Оплата в CINEMA PARK 85 MOSCOW RUS,1665

In [13]:
import numpy as np
assert np.isclose(transactions_df.loc[transactions_df[trans_col] > 0][trans_col].sum(), incomes)
assert np.isclose(transactions_df.loc[transactions_df[trans_col] < 0][trans_col].sum(), -expences)

# 2. Запроцессить гугол

In [14]:
gs_df = gsw.get_df(sheet_id, spreadsheet_name)

In [15]:
gs_df.head()

,id,Дата операции,Время операции,Сумма операции в валюте карты,Валюта карты,Сумма в валюте операции,Валюта операции,Описание операции,Номер карты,Категория,Подкатегория,Долг,Хэштэг,Комментарий
0,701a707742,"30.10, Wed",2024-10-30 20:27,-4000,₽,-4000,₽,Перевод на карту другого банка,5037,Transfer,Internal,None,None,None
1,675c171212,"30.10, Wed",2024-10-30 12:57,-2283.1,₽,-2283.1,₽,Оплата в Yandex.Lavka Moskva RUS,2475,Food & Dining,Delivery,None,None,None
2,2ef6d9a28b,"30.10, Wed",2024-10-30 11:39,-2730,₽,-2730,₽,Оплата в EGGSELLENT MOSKVA RUS,1665,Entertainment,Restaurants,None,None,None
3,dd282173e5,"29.10, Tue",2024-10-29 21:53,-900,₽,-900,₽,Внутренний перевод на договор,5427,Entertainment,Restaurants,None,None,None
4,dcb8f77afa,"29.10, Tue",2024-10-29 20:49,-50,₽,-50,₽,Внутренний перевод на договор,5044,Sport,Padel,None,None,None

In [16]:
# gs_df.to_csv("../tmp/transactions.csv")

In [17]:
if len(gs_df) > 0:
    missing_recrods = transactions_df.loc[~transactions_df['id'].isin(gs_df['id'])]

else:
    missing_recrods = transactions_df.copy()

In [18]:
missing_recrods.head()

,id,Дата операции,Время операции,Сумма операции в валюте карты,Валюта карты,Сумма в валюте операции,Валюта операции,Описание операции,Номер карты
0,75c693f91e,2025-01-18,2025-01-18 22:25:00,-3.0,₽,-3.0,₽,Оплата в Vprok.ru Perekrestok MOSCOW RUS,2475
1,bf35820f73,2025-01-18,2025-01-18 18:07:00,-1665.0,₽,-1665.0,₽,Оплата в KANTATA MOSCOW RUS,1665
2,6fd3005c5a,2025-01-18,2025-01-18 17:55:00,-1700.0,₽,-1700.0,₽,Внешний перевод по номеру телефона +79851334772,5037
3,e5aee65b11,2025-01-18,2025-01-18 16:27:00,-200.0,₽,-200.0,₽,Оплата в PARKOVKA MOSKVA RUS,1665
4,a8bfb6a013,2025-01-18,2025-01-18 14:29:00,-750.0,₽,-750.0,₽,Оплата в CINEMA PARK 85 MOSCOW RUS,1665

In [19]:
missing_recrods.shape

(351, 9)

In [20]:
missing_recrods

,id,Дата операции,Время операции,Сумма операции в валюте карты,Валюта карты,Сумма в валюте операции,Валюта операции,Описание операции,Номер карты
0,75c693f91e,2025-01-18,2025-01-18 22:25:00,-3.0,₽,-3.0,₽,Оплата в Vprok.ru Perekrestok MOSCOW RUS,2475
1,bf35820f73,2025-01-18,2025-01-18 18:07:00,-1665.0,₽,-1665.0,₽,Оплата в KANTATA MOSCOW RUS,1665
2,6fd3005c5a,2025-01-18,2025-01-18 17:55:00,-1700.0,₽,-1700.0,₽,Внешний перевод по номеру телефона +79851334772,5037
3,e5aee65b11,2025-01-18,2025-01-18 16:27:00,-200.0,₽,-200.0,₽,Оплата в PARKOVKA MOSKVA RUS,1665
4,a8bfb6a013,2025-01-18,2025-01-18 14:29:00,-750.0,₽,-750.0,₽,Оплата в CINEMA PARK 85 MOSCOW RUS,1665
...,...,...,...,...,...,...,...,...,...
346,a17edac9d9,2024-11-15,2024-11-15 00:01:00,-415.2,₽,-415.2,₽,Оплата в CITYDRIVE MOSCOW RUS,2475
347,3a6ec57ace,2024-11-14,2024-11-14 23:18:00,-2000.0,₽,-2000.0,₽,Внутренний перевод на договор,5537
348,00c5b07162,2024-11-14,2024-11-14 21:57:00,-1500.0,₽,-1500.0,₽,Внутренний перевод на договор,5537
349,00c5b07162,2024-11-14,2024-11-14 21:57:00,-1500.0,₽,-1500.0,₽,Внутренний перевод на договор,5001
358,609790e239,2024-11-13,2024-11-13 10:21:00,-13500.0,₽,-13500.0,₽,Перевод на карту другого банка,5037

In [21]:
gsw.insert_df(missing_recrods, sheet_id, spreadsheet_name, time_col=time_col, date_col=date_col)

/Users/apenkin/workspace/personal/finman/src/finman/utils/gsheet.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  missing_records[date_col] = missing_records[date_col].astype(str)
/Users/apenkin/workspace/personal/finman/src/finman/utils/gsheet.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  missing_records[time_col] = missing_records[time_col].dt.strftime('%Y-%m-%d %H:%M')

# Тестируем поиск схожих транзакиций

In [68]:
trans_col = "Сумма операции в валюте карты"
date_col = "Дата операции"
time_col = "Время операции"
spreadsheet_name = "t-bank (main)"
parse_operations = tbank.parse_operations
extract_totals = tbank.extract_total_operations